name: Keep GitHub Actions Active

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

concurrency:
  group: keep-alive
  cancel-in-progress: false

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull --rebase origin main || true

      - name: Check last commit
        run: |
          LAST_COMMIT=$(git log -1 --pretty=%B)
          if [[ "$LAST_COMMIT" == "Keep GitHub Actions alive" ]]; then
            exit 0
          fi

      - name: Keep GitHub Actions Alive
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit --allow-empty -m "Keep GitHub Actions alive"
          git push origin main || (git pull --rebase origin main && git push origin main)
