name: Generate AdBlock List

on:
  schedule:
    - cron: '0 */1 * * *'  # Co 1 godziny o pełnej godzinie
  workflow_dispatch:  # Możliwość ręcznego uruchomienia

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Zezwala na zapis do repozytorium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run the script
        run: |
          python main.py

      - name: Commit the generated files to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Optimization_suggestion.txt Full_DNS_Block.txt
          git diff --staged --quiet || (git commit -m "Update blocklist files" && git push origin main)
