name: Generate AdBlock List

on:
  schedule:
    - cron: '0 * * * *'  # Co godzinę o pełnej godzinie
  workflow_dispatch:  # To pozwala na ręczne uruchomienie workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python main.py

      # Zamiast dodawania artefaktu, zapisujemy plik do repozytorium
      - name: Commit and push FULL_lista.txt to the repository
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"
          git add FULL_lista.txt
          git commit -m "Update FULL_lista.txt"
          git push
