name: Generate AdBlock List

on:
  schedule:
    - cron: '0 * * * *'  # Co godzinę o pełnej godzinie
  workflow_dispatch:  # To pozwala na ręczne uruchomienie workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Zezwalaj na zapis do repozytorium (konieczne dla 'git push')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python main.py

      - name: Commit the generated file to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add FULL_lista.txt
          git commit -m "Update FULL_lista.txt"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
